In [20]:
import numpy as np

Jb=np.array([21,22,23,24])
print(np.__version__)
print(Jb)
print(type(Jb))

1.24.3
[21 22 23 24]
<class 'numpy.ndarray'>


In [19]:
X=[25,26,27,28] 
print(X)
print(type(X))

[25, 26, 27, 28]
<class 'list'>


In [23]:
import numpy as np

Zero_d=np.array(11)
print(Zero_d)
print(Zero_d.ndim)

11
0


In [27]:
import numpy as np

one_d=np.array([10,11,12])
print(one_d)
print(one_d.ndim)

[10 11 12]
1


In [30]:
import numpy as np

Two_d=np.array([[10,11,12],[13,14,15]])
print(Two_d)
print(Two_d.ndim)

[[10 11 12]
 [13 14 15]]
2


In [49]:
import numpy as np

three_d=np.array([[[10,11,12],[13,14,15]], [[16,17,18],[42,43,44]]])
print(three_d)
print(three_d.ndim)

[[[10 11 12]
  [13 14 15]]

 [[16 17 18]
  [42 43 44]]]
3


In [37]:
import numpy as np

multi_d=np.array([[[[10,11,12],[13,14,15]]],[[[16,17,18],[19,20,21]]]])
print(multi_d)
print(multi_d.ndim)
print(type(multi_d))

[[[[10 11 12]
   [13 14 15]]]


 [[[16 17 18]
   [19 20 21]]]]
4
<class 'numpy.ndarray'>


In [50]:
import numpy as np

multi_d=np.array([[[[[10,11,12],[13,14,15],[16,17,18],[19,20,21]]]]])
print(multi_d)
print(multi_d.ndim)
print(type(multi_d))

[[[[[10 11 12]
    [13 14 15]
    [16 17 18]
    [19 20 21]]]]]
5
<class 'numpy.ndarray'>


In [51]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0, 1])

2


In [ ]:
import numpy as np

arra = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

In [52]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, -1])

10


In [57]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:4])

[2 3 4]


In [59]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:4:2])

[2 4]


In [60]:
import numpy as np

X = np.zeros(12)
print(X)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [63]:
import numpy as np

X = np.zeros(12)
print(X)
X=X.astype(int)
print(X)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0 0 0]


In [64]:
import numpy as np

X = np.ones(12)
print(X)
X=X.astype(int)
print(X)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1]


In [66]:
import numpy as np

X = np.full(12,5)
print(X)


[5 5 5 5 5 5 5 5 5 5 5 5]


In [67]:
import numpy as np

A=np.array([[10,11,12],[13,14,15]])
print(A+2)


[[12 13 14]
 [15 16 17]]


In [68]:
import numpy as np

B=np.array([[1,2,3],[4,5,6]])
print(B-2)

[[-1  0  1]
 [ 2  3  4]]


In [69]:
import numpy as np

C=np.array([[1,2,3],[4,5,6]])
print(C*2)

[[ 2  4  6]
 [ 8 10 12]]


In [70]:
import numpy as np

D=np.array([[1,2,3],[4,5,6]])
print(D/2)

[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [71]:
import numpy as np

D=np.array([[1,2,3],[4,5,6]])
print(D//2)

[[0 1 1]
 [2 2 3]]


In [72]:
import numpy as np

E=np.array([[1,2,3],[4,5,6]])
print(E**2)

[[ 1  4  9]
 [16 25 36]]


In [73]:
import numpy as np

F=np.array([[1,2,3],[4,5,6]])
print(F.T)

[[1 4]
 [2 5]
 [3 6]]


In [75]:
import numpy as np

G=np.array([[1,2,3],[4,5,6]])
H=np.array([[-1,-2,-3],[-4,-5,-6]])
print(G+H)

[[0 0 0]
 [0 0 0]]


In [77]:
import numpy as np

G=np.array([[1,2,3],[4,5,6]])
H=np.array([[-1,-2,-3],[-4,-5,-6]])
print(G-H)

[[ 2  4  6]
 [ 8 10 12]]


In [79]:
import numpy as np

G=np.array([[1,2],[4,5]])
H=np.array([[-1,-2],[-4,-5]])
print(G*H)

[[ -1  -4]
 [-16 -25]]


In [80]:
import numpy as np

G=np.array([[1,2],[4,5]])
H=np.array([[-1,-2],[-4,-5]])
print(G/H)

[[-1. -1.]
 [-1. -1.]]


In [81]:
import numpy as np

G=np.array([[1,2],[4,5]])
H=np.array([[-1,-2],[-4,-5]])
print(G//H)

[[-1 -1]
 [-1 -1]]


In [83]:
import numpy as np

I=np.array([[1,2],[4,5]])
J=np.array([[-1,-2],[-4,-5]])
K=np.matmul(I,J)
print(K)

[[ -9 -12]
 [-24 -33]]


In [84]:
import numpy as np

I=np.array([[1,2],[4,5]])
K=np.min(I)
print(K)

1


In [85]:
import numpy as np

I=np.array([[1,2],[4,5]])
K=np.max(I)
print(K)

5


In [86]:
import numpy as np

I=np.array([[1,2],[4,5]])
K=np.sum(I)
print(K)

12


In [87]:
import numpy as np

I=np.array([[1,2],[4,5]])
K=np.mean(I)
print(K)

3.0


In [91]:
import numpy as np

I=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
K=np.median(I)
print(K)

6.5


In [93]:
import numpy as np

I=np.array([[1,2,3],[4,5,6]])
print(I.shape)

(2, 3)


In [101]:
import numpy as np

I=np.array([[1,2,3],[4,5,6]])
J=I.reshape(3,2)
print(J)
print(J.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [98]:
import numpy as np

arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]
