In [67]:
from numpy import random

x = random.randint(100)
print(x)

4


In [7]:
from numpy import random

x = random.rand()
print(x)

0.513730781641583


In [70]:
from numpy import random

x=random.randint(100, size=(5))
print(x)

[22  1  7 64 26]


In [73]:
from numpy import random

x = random.randint(100, size=(3, 5))
print(x)

[[48 59 31 21 79]
 [18 88  6 93 36]
 [85 68 56 56 73]]
