In [2]:
#Declaring Vectors in Python


from numpy import array
data = [4.0, 1.0, 2.0
]
v = array(data)
print(v)

[4. 1. 2.]


In [3]:
#Adding/Combining Vectors in Python


from numpy import array
v = array([3,2])
w = array([2,-1])
v_plus_w = v + w
print(v_plus_w)

[5 1]


In [4]:
#Multiplying/Scaling Vectors in Python

from numpy import array

v = array([3,1])

# scale the vector
scaled_v = 2.0 * v
print(scaled_v)

[6. 2.]


In [5]:
#Matrix Vector Multiplication

from numpy import array
i_hat = array([2,0])
j_hat = array([0,3])
basis = array([i_hat, j_hat]).transpose()
v = array([2,1])
w = basis.dot(v)
print(w)

[4 3]


In [2]:
#Over and Down! Over and Down!


from numpy import array
v = array([[3, 1],
[2, 0]])
w = array([[1, 2, 0],
[3, 1, 1]])

dot_product = v.dot(w)
print(dot_product)

[[6 7 1]
 [2 4 0]]


In [3]:
#Inverse Matrixes


from numpy import array
from numpy.linalg import inv
A = array([
[4, 2, 4],
[5, 3, 7],
[9, 3, 6]
])
print(inv(A))

[[-5.00000000e-01  9.86864911e-17  3.33333333e-01]
 [ 5.50000000e+00 -2.00000000e+00 -1.33333333e+00]
 [-2.00000000e+00  1.00000000e+00  3.33333333e-01]]


In [4]:
#Solving Systems of Equations

from numpy import array
from numpy.linalg import inv
# 4x + 2y + 4z = 44
# 5x + 3y + 7z = 56
# 9x + 3y + 6z = 72
A = array([
[4, 2, 4],
[5, 3, 7],
[9, 3, 6]
])
B = array([
44,
56,
72
])
X = inv(A).dot(B)
print(X)

[ 2. 34. -8.]


In [5]:
#Eigendecomposition


from numpy import array, diag
from numpy.linalg import eig, inv
A = array([
[1, 2],
[4, 5]
])
eigenvals, eigenvecs = eig(A)
print("EIGENVALUES")
print(eigenvals)
print("\nEIGENVECTORS")
print(eigenvecs)

EIGENVALUES
[-0.46410162  6.46410162]

EIGENVECTORS
[[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]
