In [1]:
import numpy

In [2]:
import numpy as np
print(np.__version__)

1.26.1


In [3]:
import numpy as np

In [4]:
a=np.array(10)   #0 dimension

In [5]:
print(a)

10


In [6]:
a = np.array([10,20,30])   #1 dimension array

In [7]:
print(a)

[10 20 30]


In [8]:
a= np.array([[10,20], [30,40]])           #2 dimension array

In [9]:
print(a)

[[10 20]
 [30 40]]


In [11]:
a=np.array([[[10,20],[30,40]],[[50,60],[70,80]]])

In [12]:
 print(a)

[[[10 20]
  [30 40]]

 [[50 60]
  [70 80]]]


In [13]:
a[0][1][0]

30

In [14]:
a=[10,20,30]
b=np.asarray(a,dtype=float)

In [15]:
print(b)


[10. 20. 30.]


In [16]:
a=[[10,20],[30,40]]
b=np.asarray(a,dtype=int,order="c")

In [17]:
print(b)

[[10 20]
 [30 40]]


In [19]:
for i in np.nditer(b):
    print(i)

10
20
30
40


In [20]:
a=[[10,20],[30,40]]
b=np.asarray(a,order="f")

In [21]:
for i in np.nditer(b):
    print(i)

10
30
20
40


In [22]:
print(b)

[[10 20]
 [30 40]]


In [23]:
a=b"welcome to NumPy"

In [27]:
np.frombuffer(a, dtype="S1",offset=9)

array([b'o', b' ', b'N', b'u', b'm', b'P', b'y'], dtype='|S1')

In [28]:
np.frombuffer(a, dtype="S1",count=2,offset=9)

array([b'o', b' '], dtype='|S1')

In [29]:
print(b)

[[10 20]
 [30 40]]


In [32]:
a=[10,30,40,50]

In [33]:
np.fromiter(a, dtype=int,count=3)

array([10, 30, 40])

In [34]:
a=np.zeros(3)

In [35]:
print(a)

[0. 0. 0.]


In [40]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
np.zeros([2,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [42]:
np.full([2,3],1)

array([[1, 1, 1],
       [1, 1, 1]])

In [43]:
np.full([2,3,4],10)

array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]])

In [44]:
np.random.rand(2,3)         #random values will be filled from 0-1

array([[0.41001201, 0.21064765, 0.53384379],
       [0.07757674, 0.69539346, 0.07440508]])

In [45]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [47]:
a=np.arange(10,20,1)

In [48]:
print(a)

[10 11 12 13 14 15 16 17 18 19]


In [49]:
np.arange(0,100,20, dtype=float)

array([ 0., 20., 40., 60., 80.])

In [50]:
a=np.arange(10,70,10)

In [51]:
print(a)

[10 20 30 40 50 60]


In [52]:
a.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [53]:
a.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [56]:
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [58]:
np.linspace(10,100,10, endpoint=False)

array([10., 19., 28., 37., 46., 55., 64., 73., 82., 91.])

In [60]:
np.linspace(10,100,10, endpoint=False,retstep=True)

(array([10., 19., 28., 37., 46., 55., 64., 73., 82., 91.]), 9.0)

In [61]:
a

array([10, 20, 30, 40, 50, 60])

In [64]:
np.logspace(1,10,10,base=2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

In [65]:
np.logspace(1,10,10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])

In [67]:
a=np.arange(10,100,10)

In [68]:
a.reshape(3,3)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [69]:
np.size(a)

9

In [70]:
a.dtype

dtype('int32')

In [71]:
b=np.array([10,20,30], dtype=float)

In [72]:
print(b)

[10. 20. 30.]


In [73]:
b.dtype

dtype('float64')

In [ ]:
#array operations

In [74]:
import numpy as np
a=np.array([[10,20,30],[40,50,60]])

In [75]:
print(a)

[[10 20 30]
 [40 50 60]]


In [76]:
a[0]

array([10, 20, 30])

In [77]:
a[1]

array([40, 50, 60])

In [78]:
a[0][1]

20

In [81]:
s=np.arange(10,100,10)

In [82]:
print(s)

[10 20 30 40 50 60 70 80 90]


In [83]:
s[2:5]

array([30, 40, 50])

In [84]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [85]:
b=np.copy(a)

In [86]:
a,b

(array([[10, 20, 30],
        [40, 50, 60]]),
 array([[10, 20, 30],
        [40, 50, 60]]))

In [87]:
c=b.view()

In [88]:
c

array([[10, 20, 30],
       [40, 50, 60]])

In [89]:
print("a=", a)
print("b=",b)
print("c=",c)

a= [[10 20 30]
 [40 50 60]]
b= [[10 20 30]
 [40 50 60]]
c= [[10 20 30]
 [40 50 60]]


In [92]:
b[0][2]=300

In [93]:
c

array([[ 10,  20, 300],
       [ 40,  50,  60]])

In [94]:
b

array([[ 10,  20, 300],
       [ 40,  50,  60]])

In [103]:
a=np.array([30,40,50,10,20,60])

In [104]:
np.sort(a)

array([10, 20, 30, 40, 50, 60])

In [105]:
a

array([30, 40, 50, 10, 20, 60])

In [106]:
a=np.sort(a)

In [107]:
a

array([10, 20, 30, 40, 50, 60])

In [108]:
a

array([10, 20, 30, 40, 50, 60])

In [120]:
d=np.dtype([('name', 'S1' ),('perc', float)])

In [121]:
marks=np.array([("ramu",95.0),("hari",75.4),("raju",98.3)],dtype=d)

In [122]:
marks

array([(b'r', 95. ), (b'h', 75.4), (b'r', 98.3)],
      dtype=[('name', 'S1'), ('perc', '<f8')])

In [123]:
np.sort(marks,order="name")

array([(b'h', 75.4), (b'r', 95. ), (b'r', 98.3)],
      dtype=[('name', 'S1'), ('perc', '<f8')])

In [124]:
a=np.arange(10,110,10)

In [125]:
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [126]:
a.reshape(2,5)

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [127]:
a=np.arange(10,130,10)

In [129]:
a

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120])

In [131]:
a.reshape(4,3)

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [132]:
a=np.array([10,20,30])

In [133]:
b=np.array([40,50,60])

In [134]:
np.append(a,b)

array([10, 20, 30, 40, 50, 60])

In [135]:
a=np.array([[10,20],[30,40]])

In [136]:
b=np.array([[50,60],[70,80]])

In [137]:
np.append(a,b)

array([10, 20, 30, 40, 50, 60, 70, 80])

In [138]:
#arithmetic operations



In [139]:
a=np.array([[10,20,30],[40,50,60]])

In [140]:
b=np.array([[1,2,3],[4,5,6]])

In [141]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [142]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [143]:
np.add(a,b)

array([[11, 22, 33],
       [44, 55, 66]])

In [144]:
c=np.array([[10,20,30]])

In [146]:
np.subtract(a,b)

array([[ 9, 18, 27],
       [36, 45, 54]])

In [147]:
np.multiply(a,b)

array([[ 10,  40,  90],
       [160, 250, 360]])

In [148]:
np.multiply(a,b) 

array([[ 10,  40,  90],
       [160, 250, 360]])

In [149]:
np.divide(a,b) 

array([[10., 10., 10.],
       [10., 10., 10.]])

In [150]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [151]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [152]:
np.exp(b)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [153]:
np.sqrt(a)

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669]])

In [154]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [155]:
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [156]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [157]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [158]:
np.exp(a)

array([[2.20264658e+04, 4.85165195e+08, 1.06864746e+13],
       [2.35385267e+17, 5.18470553e+21, 1.14200739e+26]])

In [159]:
np.exp(b)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [160]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [161]:
np.sqrt(a)

array([[3.16227766, 4.47213595, 5.47722558],
       [6.32455532, 7.07106781, 7.74596669]])

In [162]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [163]:
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [164]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [165]:
b[1][0]=40
b[1][1]=50
b[1][2]=60

In [166]:
b

array([[ 1,  2,  3],
       [40, 50, 60]])

In [167]:
a

array([[10, 20, 30],
       [40, 50, 60]])

In [168]:
np.array_equal(a,b)              #comparison

False

In [169]:
a==b                                  #comparison

array([[False, False, False],
       [ True,  True,  True]])

In [170]:
a=np.array([[10,20],[30,40],[50,60]])

In [171]:
np.min(a)

10

In [172]:
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [174]:
np.min(a,axis=1)

array([10, 30, 50])

In [175]:
np.min(a,axis=0)

array([10, 20])

In [176]:
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [177]:
np.max(a)

60

In [178]:
np.max(a,axis=0)

array([50, 60])

In [179]:
np.max(a,axis=1)

array([20, 40, 60])

In [180]:
np.sum(a)

210

In [181]:
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [182]:
np.sum(a,axis=0)

array([ 90, 120])

In [183]:
np.sum(a,axis=1)

array([ 30,  70, 110])

In [184]:
np.mean(a)

35.0

In [185]:
np.mean(a,axis=0)

array([30., 40.])

In [186]:
np.mean(a,axis=1)

array([15., 35., 55.])

In [187]:
np.median(a)

35.0

In [188]:
np.median(a,axis=0)

array([30., 40.])

In [189]:
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [190]:
np.median(a,axis=1)

array([15., 35., 55.])

In [191]:
np.var(a)

291.6666666666667

In [192]:
np.var(a,axis=0)

array([266.66666667, 266.66666667])

In [193]:
np.var(a,axis=1)

array([25., 25., 25.])

In [194]:
np.std(a)

17.07825127659933

In [195]:
np.std(a,axis=0)

array([16.32993162, 16.32993162])

In [196]:
np.std(a,axis=1)

array([5., 5., 5.])

In [200]:
import numpy as np

# Creating a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing elements using indexing
element_5 = arr[1, 1]

# Slicing rows and columns
row_2 = arr[1, :]
col_3 = arr[:, 2]

print("Array:\n", arr)
print("Element at index (1, 1):", element_5)
print("Row 2:", row_2)
print("Column 3:", col_3)


Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at index (1, 1): 5
Row 2: [4 5 6]
Column 3: [3 6 9]


In [201]:
import numpy as np

# Create a 1D array
data = np.array([3, 7, 1, 8, 5, 10, 2])

# Calculate mean and standard deviation
mean_value = np.mean(data)
std_deviation = np.std(data)

print("Data:", data)
print("Mean:", mean_value)
print("Standard Deviation:", std_deviation)


Data: [ 3  7  1  8  5 10  2]
Mean: 5.142857142857143
Standard Deviation: 3.0904725218262765


In [202]:
import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenate along rows and columns
concat_row = np.concatenate((arr1, arr2))
concat_col = np.vstack((arr1, arr2))

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Concatenation along rows:", concat_row)
print("Concatenation along columns:\n", concat_col)


Array 1: [1 2 3]
Array 2: [4 5 6]
Concatenation along rows: [1 2 3 4 5 6]
Concatenation along columns:
 [[1 2 3]
 [4 5 6]]
